[[tutorial-comparing-models]]
Comparaison des modèles de données
==================================

Une base de données Graph stocke les données structurées dans les Noeuds et Relatins d'un graphe.
Comment cela est-il comparé à d'autres modèles de persistance?
Du fait qu'un graphe est une structure générique, comparons ce à quoi d'autres modèles auraient l'air dans un graphe.

== Une base de données graphe transforme un SGBDR ==

Renversez la pile d'enregistrements d'une base de données relationnelle et vous verrez un graphe.
Là où un SGBDR est optimisé pour les données aggrégées, Neo4j est optimisé pour les données fortement connectées.

.SGBDR
image::graphdb-compare-rdbms.svg[scaledwidth="40%"]

.Base de données Graphe comme SGBDR
image::graphdb-compare-rdbms-g.svg[scaledwidth="100%"]

== Une Base de données Graphe conçoit les Stockages Clé-Valeur ==

Un modèle Clé-Valeur est très bien pour la recherche de simples valeurs ou de listes.
Quand ces valeurs sont elle-mêmes interconnectées, vous obtenez un graphe.
Neo4j vous laisse concevoir une simple structure de données en structure données interconnectées et plus complexes.

image::graphdb-compare-kvstore.svg[]

+K*+ représente une clé, +V*+ une valeur.
Notez que certaines clés pointent vers d'autres clés comme vers des valeurs.

.Graph Database as Key-Value Store
image::graphdb-compare-kvstore-g.svg[]

== Une Base de données Graphe conçoit les stockages Orientés Colonnes ==

La famille des stockages Orientés Colonnes (style BigTable) sont une évolution du modèle Clé-Valeur, utilisant des "familles" afin de grouper certaines lignes.
Enregistrées dans un graphe, ces familles peuvent devenir hiérarchiques et les relations entre les données deviennent explicites.


== Une Base de données Graphe navigue à travers un stockage orienté Documents ==

L'hiérarchie en conteneur d'une base de données orientée document conçoit facilement les données non schématisées qui peuvent être représentées en Arbre, qui est évidemment un graphe.
Référez-vous à d'autres documents (ou éléments de documents) au sein de ce même arbre et vous obtenez une représentation plus expressive de ces mêmes données.
Dans Neo4j, ces relations sont facilement naviguables.

.Document Store
image::graphdb-compare-docdb.svg[scaledwidth="75%"]

+D+=Document, +S+=Sousdocument, +V+=Valeur, +D2/S2+ = Référence à un Sousdocument dans un (autre) Document.

.Graph Database as Document Store
image::graphdb-compare-docdb-g.svg[scaledwidth="75%"]


