[[deployment-scenarios]]
Scénarios de déploiements
=========================

Neo4j peut être embarqué dans votre application (Embedded), être exécuté comme serveur autonome (Neo4j Server) ou être déployé sur plusieurs machines afin de fournir une haute disponibilité.

.Neo4j deployment options
[cols="h,,", options="header"]
|=========================================================================
|            | Instance Unique       | Instances Multiples
| Embedded   | EmbeddedGraphDatabase | HighlyAvailableGraphDatabase
| Standalone | Neo4j Server          | Neo4j Server high availability mode
|=========================================================================

== Serveur ==

Neo4j est normalé accédé comme serveur autonome, soit directement via une interface ReST ou via un pilote de langage spécifique.
Une information détaillée sur le serveur Neo4j est disponible ici <<server>>.
Pour exécuter le serveur et les systèmes embarqués en mode haute disponibilié, voyez <<ha>>.

== Embarquée (Embedded) ==

Neo4j peut être embarqué directement sur un serveur d'applications en incluant les librairies Java appropriées.
Pendant le développement, vous pouvez vous référer à l'API +http://components.neo4j.org/neo4j/{neo4j-version}/apidocs/org/neo4j/graphdb/GraphDatabaseService.html[GraphDatabaseService]+ .
Pour basculer d'une instance unique vers le mode instances multiples haute disponibilité, il vous suffit simplement de basculer de la classe concrète +http://components.neo4j.org/neo4j/{neo4j-version}/apidocs/org/neo4j/kernel/EmbeddedGraphDatabase.html[EmbeddedGraphDatabase]+ vers la +http://components.neo4j.org/neo4j-enterprise/{neo4j-version}/apidocs/org/neo4j/kernel/HighlyAvailableGraphDatabase.html[HighlyAvailableGraphDatabase]+.

