[[deployment-installation]]
Installation
============

Neo4j peut être installé comme serveur, s'exécutant aussi bien en _headless_ qu'en service système.
Pour les développeurs Java, il est également possible d'utiliser Neo4j comme bibliothèque embarquée dans votre application.

Pour plus d'informations sur l'installation de Neo4j comme serveur, référez-vous à <<server-installation>>.

Le tableau suivant énumère les éditions disponibles ainsi que leurs noms pour l'utilisation de celles-ci par des outils de gestion de dépendances.

ASTUCE: Suivez les liens dans le tableau pour plus de détails sur la configuration des dépendances avec Maven, Apache Buildr, Apache Ivy et Groovy Grape!

[[editions]]
.Neo4j editions
[options="header"]
|=======================
|Edition     |Dépendance      |Déscription  |Licence
|Community   |http://search.maven.org/#search\|gav\|1\|g%3A%22org.neo4j%22%20AND%20a%3A%22neo4j%22[org.neo4j:neo4j] |une base de données graphe ultra performante, système transactionnel ACID complet |GPLv3
|Advanced    |http://search.maven.org/#search\|gav\|1\|g%3A%22org.neo4j%22%20AND%20a%3A%22neo4j-advanced%22[org.neo4j:neo4j-advanced] |ajouté d'un système de monitoring avancé |AGPLv3
|Enterprise  |http://search.maven.org/#search\|gav\|1\|g%3A%22org.neo4j%22%20AND%20a%3A%22neo4j-enterprise%22[org.neo4j:neo4j-enterprise] |ajouté d'un système de backup en ligne ainsi que de la haute disponibilité sur une grappe de serveurs (clustering) |AGPLv3
|=======================

NOTE: Les dépendances listées ne contiennent pas l'implémentation, mais les ajoute transitivement.

Pour plus d'informations au sujet de la licence, lisez le http://neo4j.org/licensing-guide/[Guide de licence].


== Installation Embarquée (Embedded) ==

La dernière version est toujours disponible depuis http://neo4j.org/download, avec les autres distributions disponibles.
Après avoir sélectionné quelle était la version appropriée pour votre plateforme, embarquez Neo4j dans votre application en incluant le _jars_ de la bibliothèque Neo4j à votre build.
Vous pouvez soit copier les fichiers jar du dossier 'lib' du paquet téléchargé, ou alors utiliser directement les artifacts disponibles depuis le Maven Central Repository footnote:[http://repo1.maven.org/maven2/org/neo4j/]. Les versions stables et incrémentielles sont disponibles à cet endroit.

Pour plus d'information sur l'utilisation de Neo4j comme dépendance avec Maven ou un autre outil de gestion de dépendances, regardez le tableau suivant:

.Maven dependency
[source,xml] 
--------------------------------------------
<project>
...
 <dependencies>
  <dependency>
   <groupId>org.neo4j</groupId>
   <artifactId>neo4j</artifactId>
   <version>${neo4j-version}</version>
  </dependency>
  ...
 </dependencies>
...
</project>
--------------------------------------------

_Où +$\{neo4j-version}+ est la version souhaitée et le +artifactId+ est une des distributions +neo4j+, +neo4j-advanced+, +neo4j-enterprise+._

== Installation Serveur ==

Veuillez vous référer à <<serveur>> et <<server-installation>>.

