[[deployment-requirements]]
Configuration système requise
=============================

La mémoire limite la taille du graphe, les I/O disques limitent les performances lecture/écriture, comme toujours.

== Processeur ==

La performance est généralement liée à la mémoire ou aux I/O pour de larges graphes, et calcule les limites du graphe qui pourraient être allouées en mémoire.

Minimum::      Intel 486
Recommandé::   Intel Core i7


== Mémoire ==

Plus de mémoire permet de plus grands graphes, mais induit le risque de créer des opérations "Garbage Collection" assez larges.

Minimum::     1GB
Recommandé::  4-8GB

== Disque ==

A côté de sa capacité, les caractéristiques de performances du disque sont un élément majeur quant au choix du type de stockage.

Minimum::     SCSI, EIDE 
Recommandé::  SSD w/ SATA

== Système de fichiers ==

Pour un comportement ACID sain, le système de fichiers doit supporter _flush_ (fsync, fdatasync).

Minimum::      ext3 (ou similaire)
Recommandé::   ext4, ZFS

== Logiciel ==

Neo4j est basé sur Java.

Java:: 1.6+
Système d'exploitation:: Linux, Windows XP, Mac OS X

== Version JDK ==

L'exécution de Neo4j est téstée continuellement avec

* http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java Runtime Environment JRE 1.6]

